var i = 0;
var txt = 'Situado no extremo sudoeste da Europa, Portugal Continental faz fronteira apenas com um outro país, Espanha a Este e a Norte, a Oeste e a Sul é limitado pelo Atlântico. O território é dividido no continente pelo rio principal, o Tejo. A norte, a paisagem é montanhosa nas zonas do interior com planaltos, intercalados por áreas que permitem o desenvolvimento da agricultura. Ok vamos pensar um pouco........ porque estás mesmo a lêr isto? Bom eu vou me embora :)!........ NÃO!! agora vais continuar a lêr! O território dentro das fronteiras atuais da República Portuguesa tem sido continuamente povoado desde os tempos pré-históricos: ocupado por celtas, como os galaicos e os lusitanos, foi integrado na República Romana e mais tarde colonizado por povos germânicos, como os suevos e os visigodos. No século VIII, as terras foram conquistadas pelos mouros. Durante a Reconquista cristã foi formado o Condado Portucalense,  estabelecido no século IX por Vímara Peres, um vassalo do rei das Astúrias. O condado tornou-se parte do Reino de León em 1097, e os condes de Portugal estabeleceram-se como governantes independentes do reino no século XII, após a batalha de São Mamede. Com o estabelecimento do Reino de Portugal em 1139, cuja independência foi reconhecida em 1143. OK OK OK......... Vamos falar sobre ..... ... . . ... Camões? Pouco se sabe com certeza sobre a sua vida. Aparentemente nasceu em Lisboa, de uma família da pequena nobreza. Sobre a sua infância tudo é conjetura mas, ainda jovem, terá recebido uma sólida educação nos moldes clássicos, dominando o latim e conhecendo a literatura e a história antigas e modernas. Pode ter estudado na Universidade de Coimbra, mas a sua passagem pela escola não é documentada. Frequentou a corte de D. João III, iniciou a sua carreira como poeta lírico e envolveu-se, como narra a tradição, em amores com damas da nobreza e possivelmente plebeias, além de levar uma vida boémia e turbulenta. Diz-se que, por conta de um amor frustrado, autoexilou-se em África, alistado como militar, onde perdeu um olho em batalha. Voltando a Portugal, feriu um servo do Paço e foi preso. Perdoado, partiu para o Oriente. Passando lá vários anos, enfrentou uma série de adversidades, foi preso várias vezes, combateu ao lado das forças portuguesas e escreveu a sua obra mais conhecida, a epopeia nacionalista Os Lusíadas. De volta à pátria, publicou Os Lusíadas e recebeu uma pequena pensão do rei D. Sebastião pelos serviços prestados à Coroa, mas nos seus anos finais parece ter enfrentado dificuldades para se manter. Bom fim-de-semana';
var speed = 1;

function typeWriter() {
  if (i < txt.length) {
    document.getElementById("demo").innerHTML += txt.charAt(i);
    i++;
    setTimeout(typeWriter, speed);
  }
}